apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pv-claim
  namespace: media
  labels:
    k8s-app: sonarr
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    k8s-app: sonarr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: sonarr
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kubeworker
      containers:
      - name: sonarr
        image: linuxserver/sonarr:120
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        ports:
        - containerPort: 8989
          name: ui
          protocol: TCP
        volumeMounts:
        - mountPath: /downloads 
          name: downloads
        - mountPath: /tv
          name: tv
        - mountPath: /config
          name: config
      volumes:
      - name: downloads
        hostPath:
          path: "/mnt/media/downloads"
      - name: tv
        hostPath:
          path: "/mnt/media/tv"
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
  labels:
    k8s-app: sonarr
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "sonarr"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: sonarr
  type: LoadBalancer