apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis
  namespace: databases
spec:
  version: 4
  doNotPause: true
  storage:
    storageClassName: "rook-block"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 12Gi
  nodeSelector:
    kubernetes.io/hostname: kubeworker
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: monitoring
      labels:
        app: kubedb
      interval: 10s